export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_FULFILLED = 'GET_CITIES_FULFILLED';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_FULFILLED = 'REQUEST_FULFILLED';
